<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="2749" started-at="2016-09-14T04:54:05Z" finished-at="2016-09-14T04:54:08Z">
    <groups>
      <group name="loginError">
        <method signature="Login.accountLoginError()[pri:1, instance:test.Login@6767c1fc]" name="accountLoginError" class="test.Login"/>
        <method signature="Login.verifyCodeError()[pri:0, instance:test.Login@6767c1fc]" name="verifyCodeError" class="test.Login"/>
      </group> <!-- loginError -->
    </groups>
    <test name="Test" duration-ms="2749" started-at="2016-09-14T04:54:05Z" finished-at="2016-09-14T04:54:08Z">
      <class name="test.Login">
        <test-method status="FAIL" signature="verifyCodeError()[pri:0, instance:test.Login@6767c1fc]" name="verifyCodeError" duration-ms="2604" started-at="2016-09-14T12:54:05Z" finished-at="2016-09-14T12:54:08Z">
          <exception class="java.lang.Throwable">
            <full-stacktrace>
              <![CDATA[java.lang.Throwable
	at json数据结构校验不通过.(:0)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCodeError -->
        <test-method status="PASS" signature="accountLoginError()[pri:1, instance:test.Login@6767c1fc]" name="accountLoginError" duration-ms="107" started-at="2016-09-14T12:54:08Z" finished-at="2016-09-14T12:54:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accountLoginError -->
      </class> <!-- test.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
